name: 🚀 Auto Add Issue And PR To Project
on:
  issues:
    types:
      - opened

jobs:
  automate-project-card:
    runs-on: ubuntu-latest
    if: "github.event_name == 'issues'"
    steps:
      - name: Add New Issue to Project Board
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
          project: 'ISSUE'
          column: 'TODO'
          action: add
