name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, reopened, labeled, closed]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_TOKEN_TEST }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project ISSUE
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: github.event.action == 'opened'
      with:
        project: 'https://github.com/users/ding77/projects/10'

    - name: Assign issues and pull requests with `bug` label to project ISSUE
      uses: srggrs/assign-one-project-github-action@1.2.1
      if: |
        contains(github.event.issue.labels.*.name, 'BySelf') ||
        contains(github.event.issue.labels.*.name, 'Discussion') ||
        contains(github.event.issue.labels.*.name, 'question') || 
        contains(github.event.issue.labels.*.name, 'usage')
      with:
        project: 'https://github.com/users/ding77/projects/10'
        column_name: 'In Progress'
