name: Issue to Project Automation
on:
  issues:
    types: [opened, labeled]
jobs:
  automate-project-card:
    runs-on: ubuntu-latest
    steps:
      - name: Add New Issue to Project Board
        uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          project: 'ISSUE跟进大盘'
          column: 'New ISSUE'
          labels: 'bug, enhancement'
